# Generated by Django 2.2.1 on 2019-06-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('team1', models.CharField(blank=True, max_length=255, null=True)),
                ('team2', models.CharField(blank=True, max_length=255, null=True)),
                ('toss_decision', models.CharField(blank=True, max_length=255, null=True)),
                ('toss_winner', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
                ('dl_applied', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=255, null=True)),
                ('win_by_runs', models.IntegerField(blank=True, null=True)),
                ('win_by_wickets', models.IntegerField(blank=True, null=True)),
                ('player_of_the_match', models.CharField(blank=True, max_length=255, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('umpire1', models.CharField(blank=True, max_length=255, null=True)),
                ('umpire2', models.CharField(blank=True, max_length=255, null=True)),
                ('umpire3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
