# Generated by Django 2.2.1 on 2019-06-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190617_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='bye_runs',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
