# Generated by Django 2.2.1 on 2019-06-17 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190617_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('batting_team', models.CharField(blank=True, max_length=255, null=True)),
                ('bowling_team', models.CharField(blank=True, max_length=255, null=True)),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(blank=True, max_length=255, null=True)),
                ('bowler', models.CharField(blank=True, max_length=255, null=True)),
                ('non_striker', models.CharField(blank=True, max_length=255, null=True)),
                ('is_super_over', models.IntegerField()),
                ('wide_runs', models.IntegerField()),
                ('legbye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissed', models.CharField(blank=True, max_length=255, null=True)),
                ('dismissal_kind', models.CharField(blank=True, max_length=255, null=True)),
                ('fielder', models.CharField(blank=True, max_length=255, null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Match')),
            ],
        ),
    ]
