# Generated by Django 2.2.1 on 2019-06-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190617_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='match_id',
            new_name='match',
        ),
    ]
